name: "Terraform Apply - Dev"

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    uses: ./.github/workflows/reusable-terraform.yaml
    with:
      aws-environment: "dev"
      aws-region: ${{ vars.AWS_REGION }}
      terraform-command: "apply"
    secrets:
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN_DEV }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
``
